---
- name: "Check if AAS with id = {{ aas_id }} is available at registry"
  ansible.builtin.uri:
    url: "{{ aas_registry_base_url }}/api/v1/registry/{{ aas_id }}"
    method: GET
    status_code: [200, 404]
  register: get_aas_registry
  delegate_to: localhost

- name: Create AAS Descriptor at registry
  slm.aas.aas_descriptor:
    scheme: http
    host: "{{ aas_registry_host }}"
    port: "{{ aas_registry_port }}"
    aas_descriptor: "{{ aas_descriptor }}"
  when: get_aas_registry.status == 404
  delegate_to: localhost

- name: Create AAS Submodel Descriptor at registry
  slm.aas.submodel_descriptor:
    scheme: http
    host: "{{ submodel_registry_host }}"
    port: "{{ submodel_registry_port }}"
    submodel_descriptor: "{{ aas_submodel_descriptor }}"
  when: get_aas_registry.status == 404
  delegate_to: localhost

