---
- name: Init submodel_element_collection and value fact
  ansible.builtin.set_fact:
    submodel_element_collection: {}
    value: []

- name: Set Values of Submodel Element Collection
  ansible.builtin.set_fact:
    value: "{{ value + [{ 'idShort': (webcam_meta.key | replace('.', '')), 'modelType': { 'name': 'Property' }, 'valueType': 'string', 'value': webcam_meta.value }] }}"
  loop: "{{ item | dict2items }}"
  loop_control:
    loop_var: webcam_meta

- name: Set Submodel Element Collection variable
  ansible.builtin.set_fact:
    submodel_element_collection:
      idShort: "webcam-{{item.path | split('/') | last}}"
      modelType:
        name: SubmodelElementCollection
      value: "{{ value }}"

- name: Create Submodel Element "webcam-type"
  slm.aas.submodel:
    scheme: http
    host: "{{ aas_repository_host }}"
    port: "{{ aas_repository_port }}"
    submodel: "{{ submodel_element_collection }}"
    id: "{{ submodel_element_collection.idShort }}"
  delegate_to: localhost